Proc Format Lib=Formats ;
Value $SDSCKT
'A5202AR#429'='32'
'A5202AR'='32'
'A5201AR#007'='32'
'A6113AR'='16'
'A5202AR#007'='32'
'A5201AR'='32'
'A5201AR#006'='32'
'A5201A'='32'
'A6113AR#006'='16'
'A6113AR#007'='16'
'A5202AR#750'='32'
'A5202AR#006'='32'
'A5201AR#429'='32'
'A6113A'='16'
'AM223A#005'='32'
'AH337A#HTC'='16'
'AH353A#004'='32'
'AH352A#HTC'='8'
'AH406A'='8'
'AH353A#009'='32'
'AH353A#0D1'='32'
'AM223A#003'='32'
'AH406A#0D1'='8'
'AM223A#004'='32'
'AH352A#0D1'='8'
'AH352A'='8'
'AH352A#NEC'='8'
'AH353A'='32'
'AT090A'='32'
'AH337A#0D1'='16'
'AH353A#005'='32'
'AM223A'='32'
'AH337A'='16'
'AH337A#NEC'='16'
;
Run ;

Proc Format Library=Formats ;
Value RiskProfile
1 = 'Max Attention'
2 = 'Mixed'
3 = 'Migrated'
4 = 'Integrity/Blade Customer'
5 = 'Lost Customer'
6 = 'X-86 Support/Shipment'
7 = 'Only Software'
0 = 'Active on Options/Non Units'
;
Run ;

Proc Format Library=Formats ;
Value $BCSClass
'Other'='Other'
'ZMOD'='Other'
'rx16xx'='rx16,rx26'
'rx26xx'='rx16,rx26'
'rx28xx'='rx28,rx36,rx46'
'rx36xx'='rx28,rx36,rx46'
'rx46xx'='rx28,rx36,rx46'
'rx56xx'='rx56,rx66'
'rx66xx'='rx56,rx66'
'rx76xx'='rx76,rx86,rx96'
'rx86xx'='rx76,rx86,rx96'
'rx96xx'='rx76,rx86,rx96'
'D-Class'='Other'
'K-Class'='Other'
'V-Class'='Other'
'rp24xx'='rp24,rp34'
'rp34xx'='rp24,rp34'
'rp44xx'='rp44,rp54'
'rp54xx'='rp44,rp54'
'rp74xx'='rp74,rp84'
'rp84xx'='rp74,rp84'
'Alpha'='Alpha'
'DEC'='DEC'
'VAX'='VAX'
'Superdome'='Options'
'c-Class'='c-Class'
'p-Class'='p-Class'
'BL460'='BL460'
'BL60p'='BL60p'
'BL860'='BL860'
'BL870'='BL870'
'BL890'='BL890'
'Blade Enclosures / Options'='Blade Enclosures / Options'
'Telco'='Telco'
'DL38x'='DL38x,DL58x'
'DL58x'='DL38x,DL58x'
'DL7xx'='DL7xx'
'DL9xx'='DL9xx'
Other='#'
;
Run ;

Proc Format Library=Formats;

Value $MasterVarEDWFmt
'FISCAL_QTR_NM'='FISCAL_QTR_NM'
'MANUFACTURING_PRODUCT_FAMILY_I' = 'PROD_MFG_FAMILY_CD'
'MANUFACTURING_PRODUCT_FAMILY_D'='PROD_MFG_FAMILY_DESC'
'MANUFACTURING_PRODUCT_GLOBAL_B'='PROD_MFG_GBU_CD'
'MANUFACTURING_PRODUCT_GLOBAL_B02'='PROD_MFG_GBU_NM'
'MANUFACTURING_PRODUCT_LINE_IDE'='PROD_MFG_LINE_CD'
'MANUFACTURING_PRODUCT_LINE_DES'='PROD_MFG_LINE_DESC'
'MANUFACTURING_PRODUCT_MODEL_ID'='PROD_MFG_MODEL_CD'
'MANUFACTURING_PRODUCT_MODEL_DE'='PROD_MFG_MODEL_DESC'
'MANUFACTURING_PRODUCT_SUBFAMIL'='PROD_MFG_PRODUCT_CD'
'MANUFACTURING_PRODUCT_SUBFAMIL02'='PROD_MFG_PRODUCT_DESC'
'MANUFACTURING_PRODUCT_PRODUCT_'='PROD_MFG_PRODUCT_LINE_CD'
'MANUFACTURING_PRODUCT_PRODUCT_02'='PROD_MFG_PRODUCT_LINE_NM'
'MANUFACTURING_PRODUCT_IDENTIFI'='PROD_MFG_SKU_CD'
'MANUFACTURING_PRODUCT_DESCRIPT'='PROD_MFG_SKU_NM'
'MANUFACTURING_PRODUCT_TYPE_IDE'='PROD_MFG_TYPE_CD'
'MANUFACTURING_PRODUCT_TYPE_DES'='PROD_MFG_TYPE_DESC'
'NET_SHIPMENT_US_DOLLAR_AMOUNT'='SHIP_NET_USD_AMT'
'SHIP_TO_AMID_LEVEL_2_IDENTIFIE'='SHIP_TO_AMIDL2_CD'
'SHIP_TO_AMID_LEVEL_2_NAME'='SHIP_TO_AMIDL2_NAME'
'SHIP_TO_AMID_LEVEL_4_IDENTIFIE'='SHIP_TO_AMIDL4_CD'
'SHIP_TO_AMID_LEVEL_4_NAME'='SHIP_TO_AMIDL4_NAME'
'SHIP_TO_AMID_LEVEL_2_CLASS_1_C'='SHIP_TO_L2_CLASS_CD'
'SHIP_TO_AMID_LEVEL_2_CLASS_1_N'='SHIP_TO_L2_CLASS_NAME'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_03'='SHIP_TO_L2_IND_SEG_CD'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_04'='SHIP_TO_L2_IND_SEG_NAME'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_'='SHIP_TO_L2_IND_VER_CD'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_02'='SHIP_TO_L2_IND_VER_NAME'
'SHIP_TO_STANDARD_CITY_NAME'='SHIP_TO_SITE_CITY_NM'
'SHIP_TO_CUSTOMER_IDENTIFIER'='SHIP_TO_SITE_ID'
'SHIP_TO_CUSTOMER_NAME'='SHIP_TO_SITE_NAME'
'SHIP_TO_STANDARD_POSTAL_CODE'='SHIP_TO_SITE_POSTAL_CD'
'SALES_CHANNEL_ROUTE_CODE'='SLS_CHNL_RTE_CD'
'SALES_CHANNEL_ROUTE_NAME'='SLS_CHNL_RTE_NM'
'SOLD_TO_AMID_LEVEL_2_IDENTIFIE'='SOLD_TO_AMIDL2_CD'
'SOLD_TO_AMID_LEVEL_2_NAME'='SOLD_TO_AMIDL2_NAME'
'SOLD_TO_AMID_LEVEL_4_IDENTIFIE'='SOLD_TO_AMIDL4_CD'
'SOLD_TO_AMID_LEVEL_4_NAME'='SOLD_TO_AMIDL4_NAME'
'SOLD_TO_AMID_LEVEL_2_CLASS_1_C'='SOLD_TO_L2_CLASS_CD'
'SOLD_TO_AMID_LEVEL_2_CLASS_1_N'='SOLD_TO_L2_CLASS_NAME'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_03'='SOLD_TO_L2_IND_SEG_CD'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_04'='SOLD_TO_L2_IND_SEG_NAME'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_'='SOLD_TO_L2_IND_VER_CD'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_02'='SOLD_TO_L2_IND_VER_NAME'
'SOLD_TO_CUSTOMER_IDENTIFIER'='SOLD_TO_SITE_ID'
'SOLD_TO_CUSTOMER_NAME'='SOLD_TO_SITE_NAME'
'PROFIT_CENTER_NAME'='WCC_NM'
'PROFIT_CENTER_LEVEL_0_NAME'='WCC_REGION_NM'
'PROFIT_CENTER_LEVEL_2_NAME'='WCC_SUB_REG_1_NM'
'SHIPMENT_SALES_QUANTITY'='SHIP_QTY'
'DERIVED_END_CUSTOMER_AMID_LEVE'='DERIVED_END_CUSTOMER_AMID_CD'
'DERIVED_END_CUSTOMER_AMID_LEVE02'='DERIVED_END_CUSTOMER_AMID_NAME'
Other='-'
;

Value $MasterVarOSRFmt
'SHIP_QTY'='SHIP_QTY'
'FISCAL_QTR_NM'='FISCAL_QTR_NM'
'CUST_SHIP_TO_LVL_2_AMID_CD'='SHIP_TO_AMIDL2_CD'
'CUST_SHIP_TO_LVL_2_AMID_NAME'='SHIP_TO_AMIDL2_NAME'
'CUST_SHIP_TO_LVL_4_AMID_CD'='SHIP_TO_AMIDL4_CD'
'CUST_SHIP_TO_LVL_4_AMID_NAME'='SHIP_TO_AMIDL4_NAME'
'CUST_SHIP_TO_LVL_2_CLASS_CD'='SHIP_TO_L2_CLASS_CD'
'CUST_SHIP_TO_LVL_2_CLASS_NM'='SHIP_TO_L2_CLASS_NAME'
'CUST_SHIP_TO_LVL_2_INDUSTRY_SG'='SHIP_TO_L2_IND_SEG_CD'
'CUST_SHIP_TO_LVL_2_INDUSTRY_SGMT'='SHIP_TO_L2_IND_SEG_NAME'
'CUST_SHIP_TO_LVL_2_INDUSTRY_VE'='SHIP_TO_L2_IND_VER_CD'
'CUST_SHIP_TO_LVL_2_INDUSTRY_VERT'='SHIP_TO_L2_IND_VER_NAME'
'CUST_SHIP_TO_SITE_CITY_NM'='SHIP_TO_SITE_CITY_NM'
'CUST_SHIP_TO_SITE_ID'='SHIP_TO_SITE_ID'
'CUST_SHIP_TO_SITE_NAME'='SHIP_TO_SITE_NAME'
'SLS_CHNL_RTE_NM'='SLS_CHNL_RTE_NM'
'CUST_SOLD_TO_LVL_2_AMID_CD'='SOLD_TO_AMIDL2_CD'
'CUST_SOLD_TO_LVL_2_AMID_NAME'='SOLD_TO_AMIDL2_NAME'
'CUST_SOLD_TO_LVL_4_AMID_CD'='SOLD_TO_AMIDL4_CD'
'CUST_SOLD_TO_LVL_4_AMID_NAME'='SOLD_TO_AMIDL4_NAME'
'CUST_SOLD_TO_LVL_2_CLASS_CD'='SOLD_TO_L2_CLASS_CD'
'CUST_SOLD_TO_LVL_2_CLASS_NM'='SOLD_TO_L2_CLASS_NAME'
'CUST_SOLD_TO_LVL_2_INDUSTRY_SG'='SOLD_TO_L2_IND_SEG_CD'
'CUST_SOLD_TO_LVL_2_INDUSTRY_SGMT'='SOLD_TO_L2_IND_SEG_NAME'
'CUST_SOLD_TO_LVL_2_INDUSTRY_VE'='SOLD_TO_L2_IND_VER_CD'
'CUST_SOLD_TO_LVL_2_INDUSTRY_VERT'='SOLD_TO_L2_IND_VER_NAME'
'CUST_SOLD_TO_SITE_ID'='SOLD_TO_SITE_ID'
Other='-'
;

Value $AMIDDETAILS
'CUST_SHIP_TO_LVL_4_AMID_CD'='AMID_L4'
'CUST_SHIP_TO_LVL_4_AMID_NAME'='AMID_L4_NAME'
'CUST_SHIP_TO_LVL_2_INDUSTRY_SG'='AMID_L2_SEG_CD'
'CUST_SHIP_TO_LVL_2_INDUSTRY_VE'='AMID_L2_IND_CD'
'CUST_SHIP_TO_LVL_2_INDUSTRY_SGMT'='AMID_L2_SEG_NM'
'CUST_SHIP_TO_LVL_2_INDUSTRY_VERT'='AMID_L2_IND_NM'
'CUST_SHIP_TO_LVL_2_CLASS_CD'='AMID_L2_CLASS_CD'
'CUST_SHIP_TO_LVL_2_CLASS_NM'='AMID_L2_CLASS_NM'
'SHIP_TO_AMID_LEVEL_4_IDENTIFIE'='AMID_L4'
'SHIP_TO_AMID_LEVEL_4_NAME'='AMID_L4_NAME'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_03'='AMID_L2_SEG_CD'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_'='AMID_L2_IND_CD'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_04'='AMID_L2_SEG_NM'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_02'='AMID_L2_IND_NM'
'SHIP_TO_AMID_LEVEL_2_CLASS_1_C'='AMID_L2_CLASS_CD'
'SHIP_TO_AMID_LEVEL_2_CLASS_1_N'='AMID_L2_CLASS_NM'
'CUST_SOLD_TO_LVL_4_AMID_CD'='AMID_L4'
'CUST_SOLD_TO_LVL_4_AMID_NAME'='AMID_L4_NAME'
'CUST_SOLD_TO_LVL_2_INDUSTRY_SG'='AMID_L2_SEG_CD'
'CUST_SOLD_TO_LVL_2_INDUSTRY_VE'='AMID_L2_IND_CD'
'CUST_SOLD_TO_LVL_2_INDUSTRY_SGMT'='AMID_L2_SEG_NM'
'CUST_SOLD_TO_LVL_2_INDUSTRY_VERT'='AMID_L2_IND_NM'
'CUST_SOLD_TO_LVL_2_CLASS_CD'='AMID_L2_CLASS_CD'
'CUST_SOLD_TO_LVL_2_CLASS_NM'='AMID_L2_CLASS_NM'
'SOLD_TO_AMID_LEVEL_4_IDENTIFIE'='AMID_L4'
'SOLD_TO_AMID_LEVEL_4_NAME'='AMID_L4_NAME'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_03'='AMID_L2_SEG_CD'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_'='AMID_L2_IND_CD'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_04'='AMID_L2_SEG_NM'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_02'='AMID_L2_IND_NM'
'SOLD_TO_AMID_LEVEL_2_CLASS_1_C'='AMID_L2_CLASS_CD'
'SOLD_TO_AMID_LEVEL_2_CLASS_1_N'='AMID_L2_CLASS_NM'
;

Run ;

Proc Format Library=Formats;
Value $ShortFamDesSW
"F0BE"="Proliant Essentials"
"F2TZ"="Microsoft Products"
"F3KX"="VMWare"
"F3OZ"="HPC"
"F4ED"="Microsoft Products"
"F4EF"="Novell"
"F4H6"="Linux"
"F4X5"="Red Hat Linux"
"F5BP"="Control Tower"
"F63G"="Insight Control"
"F6HB"="SG"
"F6VC"="ICE Linux"
"F6W1"="XenServer"
"F71F"="Insight Dynamics"
"F74R"="Citrix"
"F7IK"="Insight Orch"
"F7IM"="Insight Recovery"
"F7WM"="Matrix"
"F7YY"="Insight Control"
"F8I1"="ICE Linux"
"F8JM"="VCEM"
;
Run ;

Proc Format Library=Formats;
Value $EBGRP
'1X','23','2M','HA','TQ','TR','NW','2K'                           = 'BCS'
'4U','LA','TN','MV','SY','SI'                                     = 'ISS'
'6H','DN','I5','I6','I7','I8','I9'                                = 'PRO'
'2E','32','33','87','8S','TE','TF','26','2F','8L','EF','D3','TH'  = 'HPSS'
'LH','LI','LM','LN','3C','LJ','1Y','LL','LK','7A'                 = 'SWD'
'7P','LP','G3','U3','G1','VS','6N','J7','J8','J9','24','25','6L',
'J2','J3','06','72','7G','91','JN','K2','K3','R4','R7','R8','UW',
'UY','4J','EA','G4','G5','TK','U4','UX','DC'                      = 'OTH'
;
Run ;

Proc Format Library=Formats ;
Value $PLStatus
'01','02','03'        = 'OPEN'
'04','04A','04B','05' = 'CLOSE'
'06','07'             = 'WEIGHTED'
Other                 = 'UnKnown'
;
Run ;
Proc Format Library=formats;

Value HpQtr
1           = 'QTR1'
11 - 12     = 'QTR1'
2  - 4      = 'QTR2'
5  - 7      = 'QTR3'
8  - 10     = 'QTR4'
;

Value QTY
0 -< 1      = 'NO'
1 -  High   = 'YES'
Other       = 'NO'
;

InValue QTY
0 -< 1      = 0
1 -  High   = 1
Other       = 0
;

Run ;

Proc Format Library=Formats fmtlib ;
Value $ESSNBU
'B1X','B23','B2M','BHA','BNW','BTQ','BTR','BVA'                  ='BCS'
'B1U','B6H','BDN','BI5','BI6','BI7','BI8','BI9'                  ='HPN'
'B4U','BJ3','BLA','BMV','BSI','BSY','BTN','BUZ'                  ='ISS'
'B1Y','B3C','B6L','BJ2','BLI','BLJ','BLK','BLL','BLM','BLN','B3Z'='SWD'
Other                                                            ='Non-Essn'
;
run ;

Proc Format Library=Formats fmtlib ;
Value $ESSNBUX
'1X','23','2M','HA','NW','TQ','TR','VA'               ='BCS'
'1U','6H','DN','I5','I6','I7','I8','I9'               ='HPN'
'4U','J3','LA','MV','SI','SY','TN','UZ'               ='ISS'
'1Y','3C','6L','J2','LI','LJ','LK','LL','LM','LN','3Z'='SWD'
Other                                                 ='Non-Essn'
;
run ;


