Proc Format Library=Formats;

Value $MasterVarEDWFmt
'FISCAL_QTR_NM'='FISCAL_QTR_NM'
'MANUFACTURING_PRODUCT_FAMILY_I' = 'PROD_MFG_FAMILY_CD'
'MANUFACTURING_PRODUCT_FAMILY_D'='PROD_MFG_FAMILY_DESC'
'MANUFACTURING_PRODUCT_GLOBAL_B'='PROD_MFG_GBU_CD'
'MANUFACTURING_PRODUCT_GLOBAL_B02'='PROD_MFG_GBU_NM'
'MANUFACTURING_PRODUCT_LINE_IDE'='PROD_MFG_LINE_CD'
'MANUFACTURING_PRODUCT_LINE_DES'='PROD_MFG_LINE_DESC'
'MANUFACTURING_PRODUCT_MODEL_ID'='PROD_MFG_MODEL_CD'
'MANUFACTURING_PRODUCT_MODEL_DE'='PROD_MFG_MODEL_DESC'
'MANUFACTURING_PRODUCT_SUBFAMIL'='PROD_MFG_PRODUCT_CD'
'MANUFACTURING_PRODUCT_SUBFAMIL02'='PROD_MFG_PRODUCT_DESC'
'MANUFACTURING_PRODUCT_PRODUCT_'='PROD_MFG_PRODUCT_LINE_CD'
'MANUFACTURING_PRODUCT_PRODUCT_02'='PROD_MFG_PRODUCT_LINE_NM'
'MANUFACTURING_PRODUCT_IDENTIFI'='PROD_MFG_SKU_CD'
'MANUFACTURING_PRODUCT_DESCRIPT'='PROD_MFG_SKU_NM'
'MANUFACTURING_PRODUCT_TYPE_IDE'='PROD_MFG_TYPE_CD'
'MANUFACTURING_PRODUCT_TYPE_DES'='PROD_MFG_TYPE_DESC'
'NET_SHIPMENT_US_DOLLAR_AMOUNT'='SHIP_NET_USD_AMT'
'SHIP_TO_AMID_LEVEL_2_IDENTIFIE'='SHIP_TO_AMIDL2_CD'
'SHIP_TO_AMID_LEVEL_2_NAME'='SHIP_TO_AMIDL2_NAME'
'SHIP_TO_AMID_LEVEL_4_IDENTIFIE'='SHIP_TO_AMIDL4_CD'
'SHIP_TO_AMID_LEVEL_4_NAME'='SHIP_TO_AMIDL4_NAME'
'SHIP_TO_AMID_LEVEL_2_CLASS_1_C'='SHIP_TO_L2_CLASS_CD'
'SHIP_TO_AMID_LEVEL_2_CLASS_1_N'='SHIP_TO_L2_CLASS_NAME'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_03'='SHIP_TO_L2_IND_SEG_CD'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_04'='SHIP_TO_L2_IND_SEG_NAME'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_'='SHIP_TO_L2_IND_VER_CD'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_02'='SHIP_TO_L2_IND_VER_NAME'
'SHIP_TO_STANDARD_CITY_NAME'='SHIP_TO_SITE_CITY_NM'
'SHIP_TO_CUSTOMER_IDENTIFIER'='SHIP_TO_SITE_ID'
'SHIP_TO_CUSTOMER_NAME'='SHIP_TO_SITE_NAME'
'SHIP_TO_STANDARD_POSTAL_CODE'='SHIP_TO_SITE_POSTAL_CD'
'SALES_CHANNEL_ROUTE_CODE'='SLS_CHNL_RTE_CD'
'SALES_CHANNEL_ROUTE_NAME'='SLS_CHNL_RTE_NM'
'SOLD_TO_AMID_LEVEL_2_IDENTIFIE'='SOLD_TO_AMIDL2_CD'
'SOLD_TO_AMID_LEVEL_2_NAME'='SOLD_TO_AMIDL2_NAME'
'SOLD_TO_AMID_LEVEL_4_IDENTIFIE'='SOLD_TO_AMIDL4_CD'
'SOLD_TO_AMID_LEVEL_4_NAME'='SOLD_TO_AMIDL4_NAME'
'SOLD_TO_AMID_LEVEL_2_CLASS_1_C'='SOLD_TO_L2_CLASS_CD'
'SOLD_TO_AMID_LEVEL_2_CLASS_1_N'='SOLD_TO_L2_CLASS_NAME'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_03'='SOLD_TO_L2_IND_SEG_CD'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_04'='SOLD_TO_L2_IND_SEG_NAME'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_'='SOLD_TO_L2_IND_VER_CD'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_02'='SOLD_TO_L2_IND_VER_NAME'
'SOLD_TO_CUSTOMER_IDENTIFIER'='SOLD_TO_SITE_ID'
'SOLD_TO_CUSTOMER_NAME'='SOLD_TO_SITE_NAME'
'PROFIT_CENTER_NAME'='WCC_NM'
'PROFIT_CENTER_LEVEL_0_NAME'='WCC_REGION_NM'
'PROFIT_CENTER_LEVEL_2_NAME'='WCC_SUB_REG_1_NM'
'SHIPMENT_SALES_QUANTITY'='SHIP_QTY'
'DERIVED_END_CUSTOMER_AMID_LEVE'='DERIVED_END_CUSTOMER_AMID_CD'
'DERIVED_END_CUSTOMER_AMID_LEVE02'='DERIVED_END_CUSTOMER_AMID_NAME'
Other='-'
;

Value $MasterVarOSRFmt
'SHIP_QTY'='SHIP_QTY'
'FISCAL_QTR_NM'='FISCAL_QTR_NM'
'CUST_SHIP_TO_LVL_2_AMID_CD'='SHIP_TO_AMIDL2_CD'
'CUST_SHIP_TO_LVL_2_AMID_NAME'='SHIP_TO_AMIDL2_NAME'
'CUST_SHIP_TO_LVL_4_AMID_CD'='SHIP_TO_AMIDL4_CD'
'CUST_SHIP_TO_LVL_4_AMID_NAME'='SHIP_TO_AMIDL4_NAME'
'CUST_SHIP_TO_LVL_2_CLASS_CD'='SHIP_TO_L2_CLASS_CD'
'CUST_SHIP_TO_LVL_2_CLASS_NM'='SHIP_TO_L2_CLASS_NAME'
'CUST_SHIP_TO_LVL_2_INDUSTRY_SG'='SHIP_TO_L2_IND_SEG_CD'
'CUST_SHIP_TO_LVL_2_INDUSTRY_SGMT'='SHIP_TO_L2_IND_SEG_NAME'
'CUST_SHIP_TO_LVL_2_INDUSTRY_VE'='SHIP_TO_L2_IND_VER_CD'
'CUST_SHIP_TO_LVL_2_INDUSTRY_VERT'='SHIP_TO_L2_IND_VER_NAME'
'CUST_SHIP_TO_SITE_CITY_NM'='SHIP_TO_SITE_CITY_NM'
'CUST_SHIP_TO_SITE_ID'='SHIP_TO_SITE_ID'
'CUST_SHIP_TO_SITE_NAME'='SHIP_TO_SITE_NAME'
'SLS_CHNL_RTE_NM'='SLS_CHNL_RTE_NM'
'CUST_SOLD_TO_LVL_2_AMID_CD'='SOLD_TO_AMIDL2_CD'
'CUST_SOLD_TO_LVL_2_AMID_NAME'='SOLD_TO_AMIDL2_NAME'
'CUST_SOLD_TO_LVL_4_AMID_CD'='SOLD_TO_AMIDL4_CD'
'CUST_SOLD_TO_LVL_4_AMID_NAME'='SOLD_TO_AMIDL4_NAME'
'CUST_SOLD_TO_LVL_2_CLASS_CD'='SOLD_TO_L2_CLASS_CD'
'CUST_SOLD_TO_LVL_2_CLASS_NM'='SOLD_TO_L2_CLASS_NAME'
'CUST_SOLD_TO_LVL_2_INDUSTRY_SG'='SOLD_TO_L2_IND_SEG_CD'
'CUST_SOLD_TO_LVL_2_INDUSTRY_SGMT'='SOLD_TO_L2_IND_SEG_NAME'
'CUST_SOLD_TO_LVL_2_INDUSTRY_VE'='SOLD_TO_L2_IND_VER_CD'
'CUST_SOLD_TO_LVL_2_INDUSTRY_VERT'='SOLD_TO_L2_IND_VER_NAME'
'CUST_SOLD_TO_SITE_ID'='SOLD_TO_SITE_ID'
Other='-'
;

Value $AMIDDETAILS
'CUST_SHIP_TO_LVL_4_AMID_CD'='AMID_L4'
'CUST_SHIP_TO_LVL_4_AMID_NAME'='AMID_L4_NAME'
'CUST_SHIP_TO_LVL_2_INDUSTRY_SG'='AMID_L2_SEG_CD'
'CUST_SHIP_TO_LVL_2_INDUSTRY_VE'='AMID_L2_IND_CD'
'CUST_SHIP_TO_LVL_2_INDUSTRY_SGMT'='AMID_L2_SEG_NM'
'CUST_SHIP_TO_LVL_2_INDUSTRY_VERT'='AMID_L2_IND_NM'
'CUST_SHIP_TO_LVL_2_CLASS_CD'='AMID_L2_CLASS_CD'
'CUST_SHIP_TO_LVL_2_CLASS_NM'='AMID_L2_CLASS_NM'
'SHIP_TO_AMID_LEVEL_4_IDENTIFIE'='AMID_L4'
'SHIP_TO_AMID_LEVEL_4_NAME'='AMID_L4_NAME'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_03'='AMID_L2_SEG_CD'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_'='AMID_L2_IND_CD'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_04'='AMID_L2_SEG_NM'
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_02'='AMID_L2_IND_NM'
'SHIP_TO_AMID_LEVEL_2_CLASS_1_C'='AMID_L2_CLASS_CD'
'SHIP_TO_AMID_LEVEL_2_CLASS_1_N'='AMID_L2_CLASS_NM'
'CUST_SOLD_TO_LVL_4_AMID_CD'='AMID_L4'
'CUST_SOLD_TO_LVL_4_AMID_NAME'='AMID_L4_NAME'
'CUST_SOLD_TO_LVL_2_INDUSTRY_SG'='AMID_L2_SEG_CD'
'CUST_SOLD_TO_LVL_2_INDUSTRY_VE'='AMID_L2_IND_CD'
'CUST_SOLD_TO_LVL_2_INDUSTRY_SGMT'='AMID_L2_SEG_NM'
'CUST_SOLD_TO_LVL_2_INDUSTRY_VERT'='AMID_L2_IND_NM'
'CUST_SOLD_TO_LVL_2_CLASS_CD'='AMID_L2_CLASS_CD'
'CUST_SOLD_TO_LVL_2_CLASS_NM'='AMID_L2_CLASS_NM'
'SOLD_TO_AMID_LEVEL_4_IDENTIFIE'='AMID_L4'
'SOLD_TO_AMID_LEVEL_4_NAME'='AMID_L4_NAME'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_03'='AMID_L2_SEG_CD'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_'='AMID_L2_IND_CD'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_04'='AMID_L2_SEG_NM'
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_02'='AMID_L2_IND_NM'
'SOLD_TO_AMID_LEVEL_2_CLASS_1_C'='AMID_L2_CLASS_CD'
'SOLD_TO_AMID_LEVEL_2_CLASS_1_N'='AMID_L2_CLASS_NM'
;

Run ;

%Macro MasterVars(MasterVarsDs,MasterVarsSource)/Store Secure ;

%Global MasterVarsKeep MasterRenameVars ;
%let MasterVarsKeep=;
%let MasterRenameVars=;

%If %Upcase(&MasterVarsSource.) eq EDW %Then %Do ;
%Let Vars=%Str('AMID_COUNTRY','AMID_NAME','AMID','AMIDL2_SUB_REGION','COUNTRY_NAME','FISCAL_QTR_NM','FISCAL_YEAR',
'FY_CALENDAR_YEAR_MONTH','MANUFACTURING_PRODUCT_FAMILY_I','MANUFACTURING_PRODUCT_FAMILY_D',
'MANUFACTURING_PRODUCT_GLOBAL_B','MANUFACTURING_PRODUCT_GLOBAL_B02','MANUFACTURING_PRODUCT_LINE_IDE',
'MANUFACTURING_PRODUCT_LINE_DES','MANUFACTURING_PRODUCT_MODEL_ID','MANUFACTURING_PRODUCT_MODEL_DE',
'MANUFACTURING_PRODUCT_SUBFAMIL','MANUFACTURING_PRODUCT_SUBFAMIL02','MANUFACTURING_PRODUCT_PRODUCT_',
'MANUFACTURING_PRODUCT_PRODUCT_02','MANUFACTURING_PRODUCT_IDENTIFI','MANUFACTURING_PRODUCT_DESCRIPT',
'MANUFACTURING_PRODUCT_TYPE_IDE','MANUFACTURING_PRODUCT_TYPE_DES','NET_SHIPMENT_US_DOLLAR_AMOUNT','SHIPMENT_SALES_QUANTITY',
'SHIP_TO_AMID_LEVEL_2_IDENTIFIE','SHIP_TO_AMID_LEVEL_2_NAME','SHIP_TO_AMID_LEVEL_4_IDENTIFIE','SHIP_TO_AMID_LEVEL_4_NAME',
'SHIP_TO_AMID_LEVEL_2_CLASS_1_C','SHIP_TO_AMID_LEVEL_2_CLASS_1_N','SHIP_TO_AMID_LEVEL_2_INDUSTRY_03',
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_','SHIP_TO_AMID_LEVEL_2_INDUSTRY_02','SHIP_TO_AMID_LEVEL_2_INDUSTRY_04','SHIP_TO_STANDARD_CITY_NAME',
'SHIP_TO_CUSTOMER_IDENTIFIER','SHIP_TO_CUSTOMER_NAME','SHIP_TO_STANDARD_POSTAL_CODE','Sales_Channel_Route_Code',
'Sales_Channel_Route_Name','SOLD_TO_AMID_LEVEL_2_IDENTIFIE','SOLD_TO_AMID_LEVEL_2_NAME','SOLD_TO_AMID_LEVEL_4_IDENTIFIE',
'SOLD_TO_AMID_LEVEL_4_NAME','SOLD_TO_AMID_LEVEL_2_CLASS_1_C','SOLD_TO_AMID_LEVEL_2_CLASS_1_N','SOLD_TO_AMID_LEVEL_2_INDUSTRY_03',
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_','SOLD_TO_AMID_LEVEL_2_INDUSTRY_04','SOLD_TO_AMID_LEVEL_2_INDUSTRY_02','SOLD_TO_CUSTOMER_IDENTIFIER',
'SOLD_TO_CUSTOMER_NAME','PROFIT_CENTER_NAME','PROFIT_CENTER_LEVEL_0_NAME','PROFIT_CENTER_LEVEL_2_NAME',
'AMID_L4','AMID_L4_NAME','AMID_L2_SEG_CD','AMID_L2_SEG_NM','AMID_L2_IND_CD','AMID_L2_IND_NM','AMID_L2_CLASS_CD','AMID_L2_CLASS_NM'
,'MANIPULATIONDATETIME','SOURCE','BUSINESSUNITS','MAINSUBREGION','INDATASETNAME','DERIVED_END_CUSTOMER_AMID_LEVE'
,'DERIVED_END_CUSTOMER_AMID_LEVE02','FY_YR_QTR'
) ;

Data
   _Null_
   ;
   Set
      &MasterVarsDs.(Obs=1)
	  ;
Length X Y $32 ;
X=VnameX('SHIP_TO_AMID_LEVEL_2_INDUSTRY_') ;
Y=VnameX('SHIP_TO_AMID_LEVEL_2_INDUSTRY_04') ;
If Missing(Y) Then ShipSegName='Y' ;
If Not Missing(X) then Call Symputx('SHIPSEGFLG',ShipSegName) ;

X=VnameX('SOLD_TO_AMID_LEVEL_2_INDUSTRY_') ;
Y=VnameX('SOLD_TO_AMID_LEVEL_2_INDUSTRY_04') ;
If Missing(Y) Then SoldSegName='Y' ;
If Not Missing(X) then Call Symputx('SOLDSEGFLG',SoldSegName) ;
Run ;

%If %SYMEXIST(SHIPSEGFLG) %Then %Do ;
    %If &SHIPSEGFLG. Ne %Str() %Then %Do ;
        %Put SHIPSEGFLG = &SHIPSEGFLG ;
        %RenameVar(&MasterVarsDs.,SHIP_TO_AMID_LEVEL_2_INDUSTRY_,SHIP_TO_AMID_LEVEL_2_INDUSTRY_03)
    %End ;
%End ;
%If %SYMEXIST(SOLDSEGFLG) %Then %Do ;
    %If &SOLDSEGFLG. Ne %Str() %Then %Do ;
        %Put SOLDSEGFLG = &SOLDSEGFLG ;
        %RenameVar(&MasterVarsDs.,SOLD_TO_AMID_LEVEL_2_INDUSTRY_,SOLD_TO_AMID_LEVEL_2_INDUSTRY_03)
    %End ;
%End ;

%End ;
%Else
%Let Vars=%Str('AMID_COUNTRY','AMID_NAME','AMID','AMIDL2_SUB_REGION','COUNTRY_NAME','FISCAL_QTR_NM','FISCAL_YEAR',
'FY_CALENDAR_YEAR_MONTH','PROD_MFG_FAMILY_CD','PROD_MFG_FAMILY_DESC','PROD_MFG_GBU_CD','PROD_MFG_GBU_NM',
'PROD_MFG_LINE_CD','PROD_MFG_LINE_DESC','PROD_MFG_MODEL_CD','PROD_MFG_MODEL_DESC','PROD_MFG_PRODUCT_CD','PROD_MFG_PRODUCT_DESC',
'PROD_MFG_PRODUCT_LINE_CD','PROD_MFG_PRODUCT_LINE_NM','PROD_MFG_SKU_CD','PROD_MFG_SKU_NM','PROD_MFG_TYPE_CD','PROD_MFG_TYPE_DESC',
'SALES_ORDER_NUMBER','SHIP_NET_USD_AMT','SHIP_QTY','CUST_SHIP_TO_LVL_2_AMID_CD','CUST_SHIP_TO_LVL_2_AMID_NAME',
'CUST_SHIP_TO_LVL_4_AMID_CD','CUST_SHIP_TO_LVL_4_AMID_NAME','CUST_SHIP_TO_LVL_2_CLASS_CD','CUST_SHIP_TO_LVL_2_CLASS_NM',
'CUST_SHIP_TO_LVL_2_INDUSTRY_SG','CUST_SHIP_TO_LVL_2_INDUSTRY_SGMT','CUST_SHIP_TO_LVL_2_INDUSTRY_VE',
'CUST_SHIP_TO_LVL_2_INDUSTRY_VERT','CUST_SHIP_TO_SITE_CITY_NM','CUST_SHIP_TO_SITE_ID','CUST_SHIP_TO_SITE_NAME',
'CUST_SHIP_TO_SITE_POSTAL_CD','SLS_CHNL_RTE_CD','SLS_CHNL_RTE_NM','CUST_SOLD_TO_LVL_2_AMID_CD','CUST_SOLD_TO_LVL_2_AMID_NAME',
'CUST_SOLD_TO_LVL_4_AMID_CD','CUST_SOLD_TO_LVL_4_AMID_NAME','CUST_SOLD_TO_LVL_2_CLASS_CD','CUST_SOLD_TO_LVL_2_CLASS_NM',
'CUST_SOLD_TO_LVL_2_INDUSTRY_SG','CUST_SOLD_TO_LVL_2_INDUSTRY_SGMT','CUST_SOLD_TO_LVL_2_INDUSTRY_VE',
'CUST_SOLD_TO_LVL_2_INDUSTRY_VERT','CUST_SOLD_TO_SITE_ID','CUST_SOLD_TO_SITE_NAME','WCC_NM','WCC_REGION_NM','WCC_SUB_REG_1_NM',
'AMID_L4','AMID_L4_NAME','AMID_L2_SEG_CD','AMID_L2_SEG_NM','AMID_L2_IND_CD','AMID_L2_IND_NM','AMID_L2_CLASS_CD','AMID_L2_CLASS_NM'
,'MANIPULATIONDATETIME','SOURCE','BUSINESSUNITS','MAINSUBREGION','INDATASETNAME','FY_YR_QTR'
) ;

%DSEXIST(&MasterVarsDs.)
%Let MasterVarsLib=&DSLIB ;
%Let MasterVarsDsNM=&DSNM ;

%PUT MasterVarsLib=&MasterVarsLib ;
%PUT MasterVarsDsNM=&MasterVarsDsNM ;
%PUT Vars = &Vars. ;

Option Nonotes ;
Proc SQL Noprint;

Select Name
      ,Case When Put(Upcase(Name),%If %Upcase(&MasterVarsSource.) eq EDW %Then %Do ; $MasterVarEDWFmt. %End ; 
                                  %Else %Do ; $MasterVarOSRFmt. %End ;) Ne '-'
            Then CatX('=',Name,Put(Upcase(Name),%If %Upcase(&MasterVarsSource.) eq EDW %Then %Do ; $MasterVarEDWFmt. %End ; 
                                                %Else %Do ; $MasterVarOSRFmt. %End ; ))
			Else '' End
  Into :MasterVarsKeep   Separated By ' '
      ,:MasterRenameVars Separated By ' '
  From Dictionary.Columns
 Where libname       ="%Cmpres(%Upcase(&MasterVarsLib.))"
   and memtype       ='DATA'
   and Memname       ="%Cmpres(%Upcase(&MasterVarsDsNM.))"
   and upcase(Name) In(&Vars.)
   ;

Quit ;
Option Notes;

%If &MasterRenameVars. Ne %Str() %Then %Do ;
    %Let MasterRenameVars=%Sysfunc(Compbl(&MasterRenameVars.)) ;
	%Put MasterRenameVars = %Str(&MasterRenameVars.) ;
%End ;
%If &MasterVarsKeep. Ne %Str() %Then %Do ;
    %Let MasterVarsKeep=%Sysfunc(Compbl(&MasterVarsKeep.)) ;
	%Put MasterVarsKeep = %Str(&MasterVarsKeep.) ;
%End ;


%Mend MasterVars ;

%Macro AMIDDETAILS(AMIDDETAILSDS)/Store Secure;

%Global AmidDetailsAssignShip AmidDetailsAssignSold ;
%Let AmidDetailsAssignShip=;
%Let AmidDetailsAssignSold=;
%DSEXIST(&AMIDDETAILSDS.)
%Let AMIDDETAILSLib=&DSLIB ;
%Let AMIDDETAILSDsNM=&DSNM ;

%Let AMIDDETAILVARSHIP=%Str('CUST_SHIP_TO_LVL_4_AMID_CD','CUST_SHIP_TO_LVL_4_AMID_NAME','CUST_SHIP_TO_LVL_2_INDUSTRY_SG',
'CUST_SHIP_TO_LVL_2_INDUSTRY_VE','CUST_SHIP_TO_LVL_2_INDUSTRY_SGMT','CUST_SHIP_TO_LVL_2_INDUSTRY_VERT','CUST_SHIP_TO_LVL_2_CLASS_CD',
'CUST_SHIP_TO_LVL_2_CLASS_NM','SHIP_TO_AMID_LEVEL_4_IDENTIFIE','SHIP_TO_AMID_LEVEL_4_NAME','SHIP_TO_AMID_LEVEL_2_INDUSTRY_03',
'SHIP_TO_AMID_LEVEL_2_INDUSTRY_','SHIP_TO_AMID_LEVEL_2_INDUSTRY_04','SHIP_TO_AMID_LEVEL_2_INDUSTRY_02','SHIP_TO_AMID_LEVEL_2_CLASS_1_C',
'SHIP_TO_AMID_LEVEL_2_CLASS_1_N') ;

%Let AMIDDETAILVARSOLD=%Str('CUST_SOLD_TO_LVL_4_AMID_CD','CUST_SOLD_TO_LVL_4_AMID_NAME','CUST_SOLD_TO_LVL_2_INDUSTRY_SG',
'CUST_SOLD_TO_LVL_2_INDUSTRY_VE','CUST_SOLD_TO_LVL_2_INDUSTRY_SGMT','CUST_SOLD_TO_LVL_2_INDUSTRY_VERT','CUST_SOLD_TO_LVL_2_CLASS_CD',
'CUST_SOLD_TO_LVL_2_CLASS_NM','SOLD_TO_AMID_LEVEL_4_IDENTIFIE','SOLD_TO_AMID_LEVEL_4_NAME','SOLD_TO_AMID_LEVEL_2_INDUSTRY_03',
'SOLD_TO_AMID_LEVEL_2_INDUSTRY_','SOLD_TO_AMID_LEVEL_2_INDUSTRY_04','SOLD_TO_AMID_LEVEL_2_INDUSTRY_02','SOLD_TO_AMID_LEVEL_2_CLASS_1_C',
'SOLD_TO_AMID_LEVEL_2_CLASS_1_N') ;

Option Nonotes ;
Proc SQL Noprint;

Select CatX('=',Put(upcase(Name),$AMIDDETAILS.),Name)
  Into :AmidDetailsAssignShip Separated By ';'
  From Dictionary.Columns
 Where libname       ="%Cmpres(%Upcase(&AMIDDETAILSLib.))"
   and memtype       ='DATA'
   and Memname       ="%Cmpres(%Upcase(&AMIDDETAILSDsNM.))"
   and upcase(Name) In(&AMIDDETAILVARSHIP.)
   ;

Select CatX('=',Put(upcase(Name),$AMIDDETAILS.),Name)
  Into :AmidDetailsAssignSold Separated By ';'
  From Dictionary.Columns
 Where libname       ="%Cmpres(%Upcase(&AMIDDETAILSLib.))"
   and memtype       ='DATA'
   and Memname       ="%Cmpres(%Upcase(&AMIDDETAILSDsNM.))"
   and upcase(Name) In(&AMIDDETAILVARSOLD.)
   ;

Quit ;
Option Notes;

%Put AmidDetailsAssignShip = &AmidDetailsAssignShip ;
%Put AmidDetailsAssignSold = &AmidDetailsAssignSold ;

%Mend AMIDDETAILS ;

%Macro UpdateShipmentMaster(InDs=NIL,OutDs=Hariship.shipmentmaster,Source=EDW,BU=NIL,Region=NIL)/Store Secure ;

%Dsexist(&InDs.)
%Let UpdateShipmentMaster_Ds  = &DSNM ;
%Let UpdateShipmentMaster_Lib = &DSLIB;

%If %Upcase(&BU.) eq NIL And %Upcase(&Region.) eq NIL %Then %Do ;
    %Put ERROR: Needs Business Unit/Region Information to load data !!! ;
	%GOTO Exit ;
%End ;

Proc SQL ;

Create table Amid_Cntry_Reg
as
Select Distinct Upcase(WCC_NM)  as Amid_Country
      ,WCC_SUB_REG_1_NM         as AMIDL2_Sub_Region
  From Hari2004.wcc_country_codes
 ;
Quit ;

%FMTMatch(Ds=Hari2004.region_country_iso,FMTName=$Cntyrnm,Var=ISO_Code,Value=Country_Name,Other='')
%FMTMatch(Ds=Amid_Cntry_Reg,FMTName=$AmidSubReg,Var=Amid_Country,Value=AMIDL2_Sub_Region,Other='')
%FmtMatch(Ds=Hari2004.industry_vert_seg,FmtName=$vertical,Var=VERTICAL,Value=Vertical_Name,Other='')
%FmtMatch(Ds=Hari2004.industry_vert_seg,FmtName=$Segment,Var=Segment,Value=Segment_Name,Other='')
%FmtMatch(Ds=Hari2004.CLASSCODE2010,FmtName=$CORPSEG,Var=L2_CLASSCODE,Value=HP_CUST_SEG,Other='')

%Let Calc_Vars=%Str('AMID_COUNTRY','AMID_NAME','AMID','AMIDL2_SUB_REGION','COUNTRY_NAME','FISCAL_QTR_NM','FISCAL_YEAR',
'FY_CALENDAR_YEAR_MONTH','MANIPULATIONDATETIME','SOURCE','BUSINESSUNITS','MAINSUBREGION','AMID_L4','AMID_L4_NAME','AMID_L2_SEG_CD',
'AMID_L2_IND_CD','AMID_L2_SEG_NM','AMID_L2_IND_NM','AMID_L2_CLASS_CD','AMID_L2_CLASS_NM','MANIPULATIONDATETIME','SOURCE',
'BUSINESSUNITS','MAINSUBREGION','INDATASETNAME') ;

Options NoNotes;
Proc SQL Noprint;

Select Name
  Into :DropVars Separated By ' '
  From Dictionary.Columns
 Where libname       ="%Cmpres(%Upcase(&UpdateShipmentMaster_Lib.))"
   and memtype       ='DATA'
   and Memname       ="%Cmpres(%Upcase(&UpdateShipmentMaster_Ds.))"
   and upcase(Name) In(&Calc_Vars.)
   ;

Quit ;
Options Notes ;

%Let Nw_UpdateShipmentMaster_Ds=%Substr(tmp_&UpdateShipmentMaster_Ds.,1,%Sysfunc(Min(%Length(tmp_&UpdateShipmentMaster_Ds.),32))) ;

%If %Upcase(&Source.) eq EDW %Then %Do ;
%AMIDDETAILS(&InDs.)
Data
    &Nw_UpdateShipmentMaster_Ds.
	;
	Set
	   &InDs.
%If %SYMEXIST(DropVars) %Then %Do ;
(
Drop=&DropVars.
)
%End ;
	   ;
Length AMID_COUNTRY $75 AMID_NAME $150 AMID $15 AMIDL2_SUB_REGION $75 COUNTRY_NAME $75 FISCAL_QTR_NM $4 FISCAL_YEAR 8 
       FY_CALENDAR_YEAR_MONTH 6 ManipulationDateTime 8 Source $8 BusinessUnits $10 MainSubRegion $30 
       AMID_L4 $15 AMID_L4_NAME $150 AMID_L2_SEG_CD $8 AMID_L2_IND_CD $8 AMID_L2_SEG_NM $50 AMID_L2_IND_NM $50
       AMID_L2_CLASS_CD $8 AMID_L2_CLASS_NM $50 INDATASETNAME $32 FY_YR_QTR $8;

If     Strip(Compress(DERIVED_END_CUSTOMER_AMID_LEVE,'?.-')) not in ('','AUDEFAULT','NOMATCH','NO MATCH') 
   And Index(DERIVED_END_CUSTOMER_AMID_LEVE,'AUDEFAULT') Eq 0
   And Strip(DERIVED_END_CUSTOMER_AMID_LEVE) Ne Strip(SHIP_TO_AMID_LEVEL_2_IDENTIFIE)
   And Strip(DERIVED_END_CUSTOMER_AMID_LEVE) Ne Strip(SOLD_TO_AMID_LEVEL_2_IDENTIFIE)
   Then Do ;
   Amid=Strip(Compress(DERIVED_END_CUSTOMER_AMID_LEVE,'?-')) ;
   Amid_Name=Strip(Compress(DERIVED_END_CUSTOMER_AMID_LEVE02,'?-')) ;
End ;
Else If Strip(Compress(SHIP_TO_AMID_LEVEL_2_IDENTIFIE,'?.-')) not in ('','AUDEFAULT','NOMATCH','NO MATCH') Then Do ;
   Amid=Strip(Compress(SHIP_TO_AMID_LEVEL_2_IDENTIFIE,'?.-')) ;
   Amid_Name=Strip(Compress(SHIP_TO_AMID_LEVEL_2_NAME,'?.-')) ;
%If &AmidDetailsAssignShip. ne %Str() %Then %Do ;
   &AmidDetailsAssignShip. ;
%End ;
   If ANYALPHA(Amid,3) eq 0 Then Do ;
      Amid_Country=Put(Substr(AMID,1,2),$Cntyrnm.) ;
      AMIDL2_Sub_Region=Put(Upcase(Amid_Country),$AmidSubReg.) ;
   End ;
End ;
Else If Strip(Compress(SOLD_TO_AMID_LEVEL_2_IDENTIFIE,'?.-')) not in ('','AUDEFAULT','NOMATCH','NO MATCH') Then Do ;
   Amid=Strip(Compress(SOLD_TO_AMID_LEVEL_2_IDENTIFIE,'?.-')) ;
   Amid_Name=Strip(Compress(SOLD_TO_AMID_LEVEL_2_NAME,'?.-')) ;
%If &AmidDetailsAssignSold. ne %Str() %Then %Do ;
   &AmidDetailsAssignSold. ;
%End ;
   If ANYALPHA(Amid,3) eq 0 Then Do ;
      Amid_Country=Put(Substr(AMID,1,2),$Cntyrnm.) ;
      AMIDL2_Sub_Region=Put(Upcase(Amid_Country),$AmidSubReg.) ;
   End ;
End ;
Else Do ;
   Amid=Coalescec(Strip(Compress(SHIP_TO_AMID_LEVEL_2_IDENTIFIE,'?-')),Strip(Compress(SOLD_TO_AMID_LEVEL_2_IDENTIFIE,'?-'))) ;
   Amid_Name=Coalescec(Strip(Compress(SHIP_TO_AMID_LEVEL_2_NAME,'?-')),Strip(Compress(SOLD_TO_AMID_LEVEL_2_NAME,'?-'))) ;
End ;

ManipulationDateTime=Datetime();
Format ManipulationDateTime Datetime32. ;
Source=Symget("Source");
BusinessUnits=Symget("BU");
MainSubRegion=Symget("Region");
InDatasetName=Symget("InDs") ;

FISCAL_QTR_NM=Tranwrd(Substr(FINANCIAL_CLOSE_FISCAL_YEAR_QU,6,2),'Q','QTR');
FY_CALENDAR_YEAR_MONTH=Compress(FINANCIAL_CLOSE_FISCAL_YEAR_MO,'FY-') ;
FISCAL_YEAR=Input(Compress(FINANCIAL_CLOSE_FISCAL_YEAR_NA,'FY-'),4.) ;
FY_YR_QTR=Cats('FY',Substr(Put(Fiscal_Year,4.),3,2),'Q',Substr(FISCAL_QTR_NM,4,1));
Rename PROFIT_CENTER_NAME=WCC_NM ;
Run ;

%MasterVars(&Nw_UpdateShipmentMaster_Ds.,EDW)

%CleanseCountryName(&Nw_UpdateShipmentMaster_Ds.,WCC_NM)

%RenameVar(&Nw_UpdateShipmentMaster_Ds.,WCC_NM,PROFIT_CENTER_NAME)

%END ;
%Else %Do ;
%AMIDDETAILS(&InDs.)
Data
    &Nw_UpdateShipmentMaster_Ds.
	;
	Set
	   &InDs.
%If %SYMEXIST(DropVars) %Then %Do ;
(
Drop=&DropVars.
)
%End ;
	   ;
Length AMID_COUNTRY $75 AMID_NAME $150 AMID $15 AMIDL2_SUB_REGION $75 COUNTRY_NAME $75 FISCAL_QTR_NM $4 FISCAL_YEAR 8 
       FY_CALENDAR_YEAR_MONTH 6 ManipulationDateTime 8 Source $8 BusinessUnits $10 MainSubRegion $30 
       AMID_L4 $15 AMID_L4_NAME $150 AMID_L2_SEG_CD $8 AMID_L2_IND_CD $8 AMID_L2_SEG_NM $50 AMID_L2_IND_NM $50
       AMID_L2_CLASS_CD $8 AMID_L2_CLASS_NM $50 INDATASETNAME $32 FY_YR_QTR $8;

If not missing(Cust_Ship_To_Lvl_2_AMID_Cd) and Upcase(Strip(Cust_Ship_To_Lvl_2_AMID_Cd)) ne 'AUDEFAULT' then do ;
   Amid=Cust_Ship_To_Lvl_2_AMID_Cd ; 
   Amid_Name=Strip(Cust_Ship_To_Lvl_2_AMID_NAME) ;
%If &AmidDetailsAssignShip. ne %Str() %Then %Do ;
   &AmidDetailsAssignShip. ;
%End ;
   
   If ANYALPHA(Amid,3) eq 0 Then Do ;
      Amid_Country=Put(Substr(AMID,1,2),$Cntyrnm.) ;
      AMIDL2_Sub_Region=Put(Upcase(Amid_Country),$AmidSubReg.) ;
   End ;
End ;
Else if not missing(Cust_Sold_To_Lvl_2_AMID_Cd) and Upcase(Strip(Cust_Sold_To_Lvl_2_AMID_Cd)) ne 'AUDEFAULT' then do ;
   Amid=Cust_Sold_To_Lvl_2_AMID_Cd ; 
   Amid_Name=Strip(Cust_Sold_To_Lvl_2_AMID_NAME) ;
%If &AmidDetailsAssignSold. ne %Str() %Then %Do ;
   &AmidDetailsAssignSold. ;
%End ;

   If ANYALPHA(Amid,3) eq 0 Then Do ;
      Amid_Country=Put(Substr(AMID,1,2),$Cntyrnm.) ;
      AMIDL2_Sub_Region=Put(Upcase(Amid_Country),$AmidSubReg.) ;
   End ;
End ;
Else Do ;
   Amid=Coalescec(Cust_Ship_To_Lvl_2_AMID_Cd,Cust_Sold_To_Lvl_2_AMID_Cd) ;
   Amid=Coalescec(Cust_Ship_To_Lvl_2_AMID_NAME,Cust_Sold_To_Lvl_2_AMID_NAME) ;
END ;

ManipulationDateTime=Datetime();
Format ManipulationDateTime Datetime32. ;
Source=Symget("Source");
BusinessUnits=Symget("BU");
MainSubRegion=Symget("Region");
InDatasetName=Symget("InDs") ;

If   Input(Substr(CALENDAR_YEAR_MONTH,5,2),2.) lt 11 then Do ;
     Fiscal_Year=Input(Substr(CALENDAR_YEAR_MONTH,1,4),4.) ;
     FY_CALENDAR_YEAR_MONTH = Cats(Put(Fiscal_Year,4.),Put(Input(Substr(CALENDAR_YEAR_MONTH,5,2),2.)+2,Z2.)) ;
	 FISCAL_QTR_NM=Put(Input(Substr(CALENDAR_YEAR_MONTH,5,2),2.),HpQtr.);
End ;
Else Do ;
     Fiscal_Year=Input(Substr(CALENDAR_YEAR_MONTH,1,4),4.)+1 ;
     FY_CALENDAR_YEAR_MONTH = Cats(Put(Fiscal_Year,4.),Put(Input(Substr(CALENDAR_YEAR_MONTH,5,2),2.)-10,Z2.)) ;
	 FISCAL_QTR_NM=Put(Input(Substr(CALENDAR_YEAR_MONTH,5,2),2.),HpQtr.);
End ;
FY_YR_QTR=Cats('FY',Substr(Put(Fiscal_Year,4.),3,2),'Q',Substr(FISCAL_QTR_NM,4,1));
Run ;

%MasterVars(&Nw_UpdateShipmentMaster_Ds.,OSR)

%CleanseCountryName(&Nw_UpdateShipmentMaster_Ds.,WCC_NM)

%End ;

Proc Append Base=&OutDs. Data=&Nw_UpdateShipmentMaster_Ds.
%If &MasterRenameVars. ne %Str() or &MasterVarsKeep. ne %Str() %Then %Do ;
(
%If &MasterVarsKeep. ne %Str()   %Then %Do ; Keep=&MasterVarsKeep.       %End ;
%If &MasterRenameVars. ne %Str() %Then %Do ; Rename=(&MasterRenameVars.) %End ;
)
%End ; 
Force ;
Run ;

%DeleteDs(&Nw_UpdateShipmentMaster_Ds.)

%EXIT:

%Mend UpdateShipmentMaster ;
